CREATE PROC DBO.PATIENTADDPICTURE
@PASSPORTID CHAR(9),
@PIC VARBINARY(MAX)
AS
BEGIN
	UPDATE PATIENT
	SET PICTURE = @PIC
	WHERE PASSPORTID = @PASSPORTID
END
GO
------------------------------------------------------------------
CREATE PROC DBO.DOCTORADDPICTURE
@PASSPORTID CHAR(9),
@PIC VARBINARY(MAX)
AS
BEGIN
	UPDATE DOCTOR
	SET PICTURE = @PIC
	WHERE PASSPORTID = @PASSPORTID
END
GO
------------------------------------------------------------------
CREATE PROC DBO.MEDICINEADDPICTURE
@NAME NVARCHAR(20),
@PIC VARBINARY(MAX)
AS
BEGIN
	UPDATE MEDICINE
	SET PICTURE = @PIC
	WHERE [NAME] = @NAME
END
GO